---
  - block: #======For RedHat ========#  
      - name: install nginx for RedHat
        yum: name=nginx state=latest
        notify: nginx start

      - name: install php for RedHat
        yum: name=php state=latest

      - name: install MariaDB for RedHat
        yum: name=mariadb-server state=latest
        notify: mariadb start

      - name: install php-fpm for RedHat
        yum: name=php-fpm state=latest
        notify: php-fpm start

      - name: copy the nginx default for RedHat
        template:
          src: /etc/ansible/roles/ansible-lemp/files/default.j2
          dest: /etc/nginx/conf.d/default.conf
        become: yes

      - name: copy the nginx.conf for RedHat
        copy:
          src: /etc/ansible/roles/ansible-lemp/files/nginx.conf
          dest: /etc/nginx/nginx.conf
        become: yes

      - name: copying t.php file for phpinfo
        copy:
          src: /etc/ansible/roles/ansible-lemp/files/t.php
          dest: /var/www/html/
        become: yes
    when: ansible_os_family == "RedHat"

  - block: #======For Debian ========#
      - name: install nginx for Debian
        apt: name=nginx state=latest
        notify: nginx start

      - name: install php for Debain
        apt: name=php state=latest

      - name: install php-fpm for Debian
        apt: name=php-fpm state=latest

      - name: install mysql-server for Debian
        apt: name=mysql-server state=latest update_cache=yes
        notify: mysql start

      - name: copy the nginx config file and restart nginx
        copy:
          src: /etc/ansible/roles/ansible-lemp/files/ubuntu/default
          dest: /etc/nginx/sites-available/default
        become: yes

      - shell: "php -n -v | head -n 1 | cut -d ' ' -f 2 | cut -d '.' -f 1,2"
        register: php_version
      - lineinfile:
          path: /etc/nginx/sites-available/default
          regexp: "^fastcgi_pass unix:"
          insertafter: "^include snippets/fastcgi-php.conf;"
          line: "fastcgi_pass unix:/var/run/php/php{{ php_version.stdout }}-fpm.sock;"

      - name: copying t.php file for phpinfo
        copy:
          src: /etc/ansible/roles/ansible-lemp/files/t.php
          dest: /var/www/html/
        become: yes
    when: ansible_os_family == "Debian"
