---
- name: nginx start
  service: name=nginx state=started

- name: php-fpm start
  service: name=php-fpm state=started
  when: ansible_os_family == "RedHat"

- name: mariadb start
  service: name=mariadb state=started
  when: ansible_os_family == "RedHat"

- name: mysql start
  service: name=mysql state=started
  when: ansible_os_family == "Debian"

- name: Install php7.3 modules
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nginx
      - php7.3-common
      - php7.3-cli
      - php7.3-dev
      - php7.3-fpm
      - php7.3-gd
      - php7.3-curl
      - php7.3-imap
      - php7.3-json
      - php7.3-opcache
      - php7.3-xml
      - php7.3-mbstring
      - php7.3-sqlite3