---
- name: nginx start
  service: name=nginx state=started

- name: php-fpm start
  service: name=php-fpm state=started
  when: ansible_os_family == "RedHat"

- name: mariadb start
  service: name=mariadb state=started
  when: ansible_os_family == "RedHat"

- name: mysql start
  service: name=mysql state=started
  when: ansible_os_family == "Debian"
